mysite/urls.py
from django.contrib import admin, auth
from django.urls import include, path
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='notes/login.html')),
    path('logout/', LogoutView.as_view(next_page='/')),
    #path('polls/', include('polls.urls')),
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
]

notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('add2', views.add2, name="add2"),
    path('entry/<int:id>', views.entry, name='entry'),
    path('tag/<str:tag>', views.tag, name='tag'),
]

notes/models.py
from django.db import models

from django.contrib.auth.models import User

# A note can have several tags that describe the category of the note
class Tag(models.Model):
    tag = models.CharField(max_length=20, unique=True)
    
    def __str__(self):
        return self.tag

class Entry(models.Model):
    subject = models.CharField(max_length=200)
    content = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('note date')
    tag = models.ManyToManyField(Tag)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.subject

notes/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

#from . import signals

import logging

from .models import Tag, Entry

log = logging.getLogger("notes")

@login_required
def index(request):
    entries = Entry.objects.filter(owner=request.user)
    tags = Tag.objects.all()
    template = loader.get_template('notes/index.html')
    context = {
        'entries': entries,
        'tags': tags,
    }
    return HttpResponse(template.render(context,request))

@login_required
def tag(request, tag):
    entries = Entry.objects.filter(tag__tag=tag)
    template = loader.get_template('notes/tag.html')
    context = {
        'entries': entries,
        'tag': tag,
    }
    return HttpResponse(template.render(context,request))

@login_required
def entry(request, id):
    try:
        action = request.POST['action']
        if action == "delete":
            e=Entry.objects.get(pk=id)
            e.delete()
            #log.info("Deleting an entry")
            return HttpResponseRedirect("/")
    except (KeyError):
        pass
    
    context = {'id' : id }
    try:
        e = Entry.objects.get(pk=id)
        context['e']=e
    except ObjectDoesNotExist:
        pass
    template = loader.get_template('notes/entry.html')

    return HttpResponse(template.render(context,request))

@login_required
def add(request):
#    entries = Entry.objects.filter(tags__tag__exact=tag)
    template = loader.get_template('notes/add.html')
    tags = Tag.objects.all()
    context = {
#        'entries': entries,
        'tags': tags,
    }
    return HttpResponse(template.render(context,request))

@login_required
def add2(request):
    try:
        subject = request.POST['subject']
        content = request.POST['content']
    except (KeyError):
        # Redisplay the question voting form.
        tags = Tag.objects.all()
        return render(request, 'notes/add.html', {
            'tags' : tags,
            'error_message': "You did not provide both subject and content.",
        })
    else:
        # Check the input
        if subject == "" or content == "":
            tags = Tag.objects.all()
            return render(request, 'notes/add.html', {
                'tags' : tags,
                'error_message': "You did not provide both subject and content.",
            }) 
        tags = request.POST.getlist('tag')

        # Create model instances
        e = Entry(owner=request.user, subject=subject, content=content, pub_date=timezone.now())
        e.save()
        if tags:
            for tag in tags:
                try:
                    t=Tag.objects.get(tag=tag)
                    e.tag.add(t)
                except Tag.DoesNotExist:
                    e.tag.create(tag=tag)
        e.save()

        #return HttpResponseRedirect("/notes/entry/%i" % e.id)
        return redirect('notes:entry', id=e.id)

notes/templates/notes/add.html
<h1>Add new entry</h1>
<a href="/notes/">Top level</a>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'notes:add2' %}" method="post">
{% csrf_token %}


<input type="submit" value="Add" />
<input type="text" name="subject" id="add_subject" value="dummy" />
<label for="subject">Subject</label><br />

<br/>

<textarea name="content" rows="10" cols="30"></textarea>
<label for="content">Content</label><br />

<br/>
<div id="tags">
{% for tag in tags %}
<div>
<input type="checkbox" name="tag" id="add_tag_{{tag}}" value="{{tag}}" />
<label for="add_tag_{{tag}}">{{tag}}</label>
</div>
<br />
{% endfor %}
</div>

<div id="create_new_tag">
  <input type="text" id="new_tag"/>
  <input type="button" value="Create new tag" onclick="create_tag(this)" />
</div>

</form>
<script>
  function create_tag(e) {
    value=document.getElementById("new_tag").value;
    if (value=="")
      return;
    divs=document.getElementById("tags")
    d=document.createElement("div")
    d.innerHTML = '<input type="checkbox" name="tag" id="add_tag_'+value+'" value="'+value+'" /><label for="add_tag_'+value+'">'+value+'</label>';
    divs.appendChild(d)
    document.getElementById("new_tag").value = "";
    
  }
  
  </script>

notes/templates/notes/entry.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />

<h1>Note with id {{id}}</h1>
<a href="{% url 'notes:index' %}">Top level</a>
{% if e %}
  <ul class="content_list">
    <li>
      <form id="delete_form" method="post" action="{% url 'notes:entry' id %}">
	{% csrf_token %}
	<input type="hidden" name="action" value="delete" \>
	<input type="button" value="Delete note"
	     onclick='document.getElementById("delete_form").submit()' />
      </form>
      <div class"entry">
	<div class="message_heading">
	<span class="left_side">{{e.subject }}
	<span class="right_side">{{e.pub_date}}</span>
	</div>
	<div class="content">
	  {{e.content}}
	</div>
	{% if e.tag.all %}
          <div class="tags">
            {% for tag in e.tag.all %}
              <a href="{% url 'notes:tag' tag.tag %}">{{ tag.tag }}</a>
	    {% endfor %}
	  </div>
        {% endif %}
      </div>
    </li>
  </ul>
{% else %}
  <p>Note not available.</p>
{% endif %}
  

notes/templates/notes/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />

<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

<h1>List of all notes</h1>

        <table>
		<tr>
		<th style="text-align:left">Username: <td>{{user.username}} 
		</table>


        <form action='logout/' method="POST">
			{% csrf_token %}
            <input type="submit" value="Logout"/>
        </form>
	
<a href="{% url 'notes:add' %}">Add new message</a>

{% if tags %}
Tags:
{% for t in tags %}
   <a class="tag" href="{% url 'notes:tag' t.tag %}">{{t.tag}}</a>
{% endfor %}
{% endif %}

{% if entries %}
  <ul class="content_list">
    {% for e in entries %}
    <li>
      <div class"entry">
	<div class="message_heading">
	<span class="left_side"><a href="{% url 'notes:entry' e.id%}">{{e.subject }}</a></span>
	<span class="right_side">{{e.pub_date}}</span>
	</div>
	<div class="content">
	  <!-- https://docs.djangoproject.com/en/3.1/ref/templates/language/#automatic-html-escaping -->
	  {% autoescape off %}
	  {{e.content}}
	  {% endautoescape %}
	</div>
	{% if e.tag.all %}
          <div class="tags">
            {% for tag in e.tag.all %}
              <a href="{% url 'notes:tag' tag.tag %}">{{ tag.tag }}</a>
	    {% endfor %}
	  </div>
        {% endif %}
      </div>
    </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No notes available.</p>
{% endif %}

notes/templates/notes/login.html
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

notes/templates/notes/tag.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />

<h1>List of all notes with tag {{tag}}</h1>
<a href="{% url 'notes:index' %}">Top level</a>
{% if entries %}
  <ul class="content_list">
    {% for e in entries %}
    <li>
      <div class"entry">
	<div class="message_heading">
	<span class="left_side">{{e.subject }}
	<span class="right_side">{{e.pub_date}}</span>
	</div>
	<div class="content">
	  {{e.content}}
	</div>
	{% if e.tag.all %}
        <div class="tags">
	  Tags:
            {% for tag in e.tag.all %}
              <a href="{% url 'notes:tag' tag.tag %}">{{ tag.tag }}</a>
	    {% endfor %}
	  </div>
        {% endif %}
      </div>
    </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No notes available.</p>
{% endif %}